server {
    listen 80;

    # URL da landing Page principal
    location / {
        proxy_pass http://react-frontend:3000;
    }

    # URL que o usuario irá acessar quando for fazer sua autenticação no sistema
    location /auth/ {
        proxy_pass http://auth-api:8080/;
    }

    # URL que o usuario estará apos fazer a autenticação, que no caso é sua To_Do_List pessoal.
    location /toDo/ {
        proxy_pass http://todo-api:8081/;
    }
}